language: android
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
    - extra-android-support
    - sys-img-armeabi-v7a-android-22

jdk:
  - oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - ./wait_for_emulator
  - adb shell input keyevent 82 &

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/